context:
  name: aider-chat
  version: "0.85.5"
  python_min: "3.10"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  # url: https://github.com/Aider-AI/aider/archive/refs/tags/v${{ version }}.tar.gz
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: 5bd0a9e48acb56a6ca00589cdce4e9f450b11b8721230ae4230fca0f86e475a6
  patches:
    # upstream automatically update its requirements.txt and has strict == matching
    - patches/relax-too-strict-requirements.patch

build:
  noarch: python
  script:
    content:
      - ${{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv
    env:
      SETUPTOOLS_SCM_PRETEND_VERSION: ${{ version }}
  number: 0
  python:
    entry_points:
      - aider = aider.main:main

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools >=68
    - setuptools-scm
  run:
    - aiohttp ==3.12.15
    - aiosignal ==1.4.0
    - backoff
    - beautifulsoup4 ==4.13.4
    - certifi ==2025.8.3
    - configargparse
    - diff-match-patch
    - diskcache
    - flake8
    - frozenlist ==1.7.0
    - gitdb
    - gitpython
    - google-ai-generativelanguage
    - google-api-core
    - google-api-python-client ==2.178.0
    - google-auth ==2.40.3
    - google-auth-httplib2
    - google-generativeai
    - googleapis-common-protos
    - grep-ast ==0.9.0
    - grpcio >=1.74.0
    - grpcio-status >=1.71.2
    - huggingface_hub ==0.34.3
    - importlib-metadata <8.0.0
    - importlib-resources
    - json5
    - jsonschema
    - litellm ==1.75.0
    - mccabe
    - mixpanel
    - multidict ==6.6.3
    - networkx ==3.4.2
    - numpy ==1.26.4
    - openai ==1.99.1
    - oslex
    - packaging ==25.0
    - pathspec
    - pexpect
    - pillow ==11.3.0
    - posthog ==6.4.1
    - prompt_toolkit ==3.0.51
    - protobuf >=5.29.5
    - psutil
    - pydub
    - pycodestyle
    - pydantic
    - pydantic-core
    - pyflakes
    - pypandoc
    - pyperclip
    - pysoundfile
    - python >=${{ python_min }}
    - python-sounddevice
    - PyYAML
    - rich
    - rpds-py ==0.27.0
    - scipy >=1.15.2
    - shtab
    - smmap
    - socksio
    - python-sounddevice
    - soupsieve
    - tokenizers ==0.21.4
    - tree-sitter-c-sharp
    - tree-sitter-embedded-template
    - tree-sitter-language-pack ==0.9.0
    - tree-sitter-yaml >=0.7.1
    - typing-extensions ==4.14.1
    - watchfiles

tests:
  - python:
      imports:
        - aider
        - aider.main
      pip_check: true
      python_version: ${{ python_min }}.*
  - script:
      - aider --help
      - if: unix
        then:
          - cp -r aider/website ${CONDA_PREFIX}/lib/python${{ python_min }}/site-packages/aider
          # A few tests fail
          - (AIDER_ANALYTICS=false python -m pytest tests/ -k "not test_model_accepts_settings_attribute and not TestRepoMapAllLanguages and not test_no_verify_ssl_sets_model_info_manager and not test_scrape_with_playwright_error_handling and not test_deprecated_args_show_warnings and not test_model_alias_in_warning and
            not test_get_repo_map_with_identifiers and not test_repo_map_refresh_auto and not test_repo_map_refresh_files and not test_no_verify_ssl_flag_sets_model_info_manager and not test_cmd_web_imports_playwright and not test_scrape_actual_url_with_playwright and not test_scrape_self_signed_ssl") || true
    requirements:
      run:
        - botocore
        - pip
        - pyopenssl
        - pytest
        - python ${{ python_min }}.*
        - urllib3
    files:
      source:
        - tests/
        - aider/website/

about:
  homepage: https://github.com/Aider-AI/aider
  summary: 'aider is AI pair programming in your terminal.'
  description: |
    Aider lets you pair program with LLMs to start a new
    project or build on your existing codebase.
  license: Apache-2.0
  license_file: LICENSE.txt
  documentation: https://aider-chat.org/
  repository: https://github.com/Aider-AI/aider

extra:
  recipe-maintainers:
    - MementoRC
